### ISSUE TITLE
Improvement of recordCell

### ISSUE THREAD

**Issue by victoriagjh** [victoriagjh/RECO_NOTE#4]
## Todo

- [ ] get Record File Size
- [ ] play the file when click the recordCell contentView
- [ ] erase File directly by swiping the cell

## Linked Issue

#1 RecordCell design
